extends Node
## First-party engagement analytics via the GA4 Measurement Protocol.
##
## Why Measurement Protocol (and NOT the Firebase iOS SDK): the iOS Xcode
## project is REGENERATED by `godot --export` on every deploy (build/ is
## gitignored), so anything injected into it — the Firebase SDK, CocoaPods —
## gets wiped each build. MP is pure GDScript over HTTPRequest: it survives
## re-export, needs no native plugin, and feeds the same GA4 property Firebase
## Analytics uses.
##
## Privacy: we mint our OWN random client id (no IDFV, no Firebase Installation
## ID), persisted in user://. Events are anonymous product-interaction only —
## no PII, no ad SDK, no cross-app/site joining → NOT "tracking" per Apple's
## definition, no ATT prompt. Matches the casual-game privacy profile.
##
## SETUP (one-time, in the GA4 web console):
##   1. Create a GA4 property (or reuse one) with a **Web** data stream.
##   2. Copy the stream's Measurement ID (starts with "G-") → MEASUREMENT_ID.
##   3. Admin → Data Streams → (stream) → Measurement Protocol API secrets →
##      Create → copy the secret value → API_SECRET.
## Until both are filled in, analytics is silently disabled (no-op).

# --- Credentials (paste from your GA4 Web data stream) ---
const MEASUREMENT_ID := ""   # e.g. "G-XXXXXXXXXX"
const API_SECRET := ""       # e.g. "abcdEFGH_ijklMNOP-qrst"

const ENDPOINT := "https://www.google-analytics.com/mp/collect"
const ID_PATH := "user://analytics_id.txt"

var _client_id: String = ""
var _session_id: String = ""
var _http: HTTPRequest
var _enabled: bool = false

func _ready() -> void:
	_enabled = _should_enable()
	if not _enabled:
		return
	_client_id = _load_or_make_client_id()
	_session_id = str(int(Time.get_unix_time_from_system()))
	_http = HTTPRequest.new()
	add_child(_http)

	# Wire to existing GameState signals so we don't touch game logic. These fire
	# the engagement funnel: discoveries, building (quest) completions, and the
	# all-inventions campaign finale.
	GameState.invention_discovered.connect(_on_invention_discovered)
	GameState.quest_completed.connect(_on_quest_completed)

	log_event("game_open", {
		"app_version": ProjectSettings.get_setting("application/config/version", "dev"),
	})

# --- Public API ---

func log_event(event_name: String, params: Dictionary = {}) -> void:
	if not _enabled:
		return
	var url := "%s?measurement_id=%s&api_secret=%s" % [ENDPOINT, MEASUREMENT_ID, API_SECRET]
	var body := JSON.stringify(build_body(event_name, params))
	# Fire-and-forget. MP returns 204 No Content on success; we don't block on it.
	_http.request(url, ["Content-Type: application/json"], HTTPClient.METHOD_POST, body)

func build_body(event_name: String, params: Dictionary) -> Dictionary:
	# Pure (no network) so it's unit-testable. GA4 needs session_id +
	# engagement_time_msec on every event for it to count as an engaged session
	# and show up in standard reports (not just Realtime).
	var p := params.duplicate()
	p["session_id"] = _session_id
	p["engagement_time_msec"] = 1
	return {
		"client_id": _client_id,
		"events": [{"name": event_name, "params": p}],
	}

# --- Signal handlers ---

func _on_invention_discovered(id: StringName) -> void:
	log_event("invention_discovered", {
		"invention_id": String(id),
		"total_discovered": GameState.discovered.size(),
	})
	# Campaign finale: all inventions discovered. Items.all_inventions() is the
	# canonical full list (same one the trophy grid iterates).
	var total: int = Items.all_inventions().size() if Items.has_method("all_inventions") else 0
	if total > 0 and GameState.discovered.size() >= total:
		log_event("campaign_complete", {"total": total})

func _on_quest_completed(npc_id: StringName) -> void:
	var npc = Npcs.by_id(npc_id)
	var params := {"npc_id": String(npc_id)}
	if npc != null:
		params["building"] = npc.building_label
		params["level"] = npc.level + 1  # 1-based for readability in reports
	log_event("building_complete", params)

# --- Internals ---

func _should_enable() -> bool:
	if MEASUREMENT_ID == "" or API_SECRET == "":
		return false
	# Never phone home from editor plays, headless tools, or the dev render/test
	# harnesses (--test-hints, --shoot, --capture-transition, --export...).
	if OS.has_feature("editor"):
		return false
	if DisplayServer.get_name() == "headless":
		return false
	for a in OS.get_cmdline_args() + OS.get_cmdline_user_args():
		if a.begins_with("--test-hints") or a.begins_with("--shoot") \
			or a.begins_with("--capture-transition") or a.begins_with("--export"):
			return false
	return true

func _load_or_make_client_id() -> String:
	if FileAccess.file_exists(ID_PATH):
		var f := FileAccess.open(ID_PATH, FileAccess.READ)
		if f != null:
			var s := f.get_as_text().strip_edges()
			if s != "":
				return s
	# GA4-style client id: "<random>.<first-seen-unix>". Stable across game
	# resets (we never delete this file in GameState.reset()).
	var cid := "%s.%d" % [_random_hex(16), int(Time.get_unix_time_from_system())]
	var w := FileAccess.open(ID_PATH, FileAccess.WRITE)
	if w != null:
		w.store_string(cid)
	return cid

func _random_hex(byte_count: int) -> String:
	var out := ""
	for i in byte_count:
		out += "%02x" % (randi() % 256)
	return out
